name: Tests

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
      -
        name: Check code formatting
        run: cargo fmt --all -- --check
      -
        name: Check code correctness
        run: cargo clippy --workspace --verbose -- -D warnings
      -
        name: Build binaries
        run: cargo build --workspace --verbose
      -
        name: Test binaries
        run: cargo test --workspace --verbose
